package ge.tbc.testautomation.constants;

import java.math.BigDecimal;
import java.util.List;

public class Constants {
    public static final String BASE_URL = "https://www.tbcbank.ge",
            API_BASE_URL = "https://apigw.tbcbank.ge",
            EXCHANGE_RATES_BASE_PATH = "/api/v1/exchangeRates",
            GET_EXCHANGE_RATE_ENDPOINT = "/getExchangeRate",
            REGIONS_ENDPOINT = "/api/v1/atmsAndBranches/regions",
            DIGITAL_BANK_EN = "Digital Bank",
            LANG_KA = "ka",
            LANG_EN = "en",
            LANG_ATTRIBUTE = "lang",
            CURRENCY_TITLE_KA = "ვალუტის კურსი",
            CURRENCY_TITLE_EN = "Exchange Rates",
            BUY_LABEL_EN = "Buy",
            BUY_LABEL_KA = "ყიდვა",
            SELL_LABEL_EN = "Sell",
            SELL_LABEL_KA = "გაყიდვა",
            FROM_CURRENCY_USD = "USD",
            TO_CURRENCY_GEL = "GEL",
            LOAN_SEED_SCRIPT_PATH = "testdata/loan_test_data.sql",
            MYBATIS_CONFIG_PATH = "mybatis/mybatis-config.xml",
            DB_URL = "jdbc:h2:./data/tbcdb;DB_CLOSE_ON_EXIT=FALSE",
            DB_USER = "sa",
            DB_PASSWORD = "",
            ERROR_MYBATIS_CONFIG_LOAD_FAILED = "Failed to load mybatis-config.xml",
            ERROR_LOAN_SCHEMA_INIT_FAILED = "Failed to initialize loan_test_data schema",
            ERROR_LOAN_SEED_FAILED = "Failed to seed loan_test_data from SQL file",
            PAGES_ENDPOINT = "/api/v1/sites/pages/",
            CONSUMER_LOAN_PAGE_ID = "4y4ZHuVsbZGrdtU9hV8jn2",
            LOCALE_KA_GE = "ka-GE",
            BRANCHES_PAGE_PATH = "/atms&branches",
            BRANCH_SEARCH_ENDPOINT = "/api/v1/atmsAndBranches/list",
            BRANCH_SEARCH_METHOD = "POST",
            BRANCH_ATM_TAB = "ბანკომატები",
            BRANCH_FILTER_ATM = "ATM",
            INVALID_ENDPOINT = "/getExchangeRates",
            CITY_TBILISI = "Tbilisi",
            CITY_BATUMI = "Batumi",
            CITY_KUTAISI = "Kutaisi",
            MISMATCH_MESSAGE = "Mismatch at index ",
            FAILED_MESSAGE = "Failed to parse JSON: ",
            EXPECTED = "Expected: ",
            ACTUAL = ", Actual: ",
            ERROR_NO_ATM_REQUEST = "No request was sent after selecting the ATM tab",
            ERROR_UNEXPECTED_ENDPOINT = "Unexpected endpoint: ",
            ERROR_UNEXPECTED_FILTER = "Unexpected filter in request body: ",
            ERROR_NO_LIST_IN_RESPONSE = "No list found in response",
            ERROR_EMPTY_RESPONSE_LIST = "Response list is empty",
            REGION_COUNT_MESSAGE = " count",
            REGION_COORDINATES_MESSAGE = " coordinates",
            REGION_NORTH_EAST_MESSAGE = " northEast",
            REGION_SOUTH_WEST_MESSAGE = " southWest",
            ERROR_CTA_SECTION_NOT_FOUND = "Section not found in API response: ",
            ERROR_SITE_PAGE_NOT_DESERIALIZED = "SitePage was not deserialized",
            ERROR_SLUG_EMPTY = "Slug is empty",
            ERROR_CTA_TITLE_EMPTY = "CTA title is empty",
            ERROR_CTA_LIST_EMPTY = "CTA list is empty",
            ERROR_CTA_LIST_BLANK_LABELS = "CTA list contains blank labels",
            ISO1_PARAM = "Iso1",
            ISO2_PARAM = "Iso2",
            LOCALE_PARAM = "locale",
            PAGE_ID_PATH_PARAM = "pageId",
            VALID_SEARCH_TEXT = "სესხი",
            INVALID_SEARCH_TEXT = "zj5415",
            EMPTY_SEARCH_TEXT = " ",
            NO_RESULTS_MESSAGE = "ვერაფერი ვიპოვეთ",
            ZERO_CENTS = "00",
            TRAILING_ZERO = "0",
            DECIMAL_POINT_REGEX = "\\.",
            OPTIONAL_THOUSANDS_SEPARATOR_REGEX = ",?",
            OPTIONAL_ZERO_CENTS_REGEX = "(?:\\.0{1,2})?",
            OPTIONAL_TRAILING_ZERO_REGEX = "0?",
            ALTERNATION = "|",
            AMOUNT_PREFIX_REGEX = "(?<![\\d.,])(?:",
            AMOUNT_SUFFIX_REGEX = ")(?!\\.?\\d)",
            CONSUMER_LOAN_CTA_SECTION_KEY = "site-loans-consumer-loan-cta-section";
    public static final List<String> LOAN_TERMS_CAPTIONS = List.of(
            "სესხის ლიმიტი",
            "სესხის ვადა",
            "საპროცენტო განაკვეთი",
            "ეფექტური საპროცენტო განაკვეთი",
            "თანხის გატანის საკომისიო",
            "გაცემის საკომისიო",
            "წინსწრების საკომისიო",
            "სიცოცხლის დაზღვევა"
    );
    public static final List<String> LOAN_TERMS_TITLES = List.of(
            "200 - 80,000 ლარი",
            "3 - 48 თვე",
            "9.9%-დან",
            "18%-დან",
            "0 - 0.6% მდე - ანგარიშის ტარიფის მიხედვით",
            "30 სექტემბრის ჩათვლით გაცემის საკომისიო 0%",
            "არაუმეტეს 0%",
            "სიცოცხლის დაზღვევის გადასახდელი განისაზღვრება ფიქსირებული თანხით და დამოკიდებულია სესხის თანხის მოცულობაზე:"
    );

    public static final BigDecimal CENT = new BigDecimal("0.01");

    public static final int MONEY_AMOUNT = 10000,
            HTTP_OK = 200,
            MONTH_AMOUNT = 24,
            CENT_SCALE = 2,
            THOUSANDS_GROUP_SIZE = 3;
    public static final double NOMINAL_RATE = 9.9,
            GEORGIA_LAT_MIN = 41.0,
            GEORGIA_LAT_MAX = 43.7,
            GEORGIA_LON_MIN = 40.0,
            GEORGIA_LON_MAX = 47.0,
            FORMULA_TOLERANCE = 0.1,
            DB_TOLERANCE = 0.5;

}